# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'reactNativeSaasSeed' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeSaasSeed
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Libs
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  # Daba error en build. Funciona linkeando manualmente (importando el projecto desde Libs)
  # pod 'react-native-config', :path => '../node_modules/react-native-config'

end

# FIX to react-native-maps linking error duplicate symbols
post_install do |installer|
    installer.pods_project.targets.each do |target|
        # Add extra code if using google maps. See example Podfile in react-native-maps repo
        if target.name == "React"
            target.remove_from_project
        end
    end
end
